name: Publish zertiair application

on:
  push:
    branches:
      - master

jobs:
  deploy_backend:
    name: Deploy service
    runs-on: self-hosted
    steps:
      - name: Pulling repo
        run: |
          cd /home/megatro/apps/dockers/zertiair/
          echo "Start GIT PULL"
          git restore .
          git pull
          echo "End GIT PULL"
      - name: Publish backend
        run: |
          cd /home/megatro/apps/dockers
          echo "Start deploying zertiair api v2"
          docker compose up -d --force-recreate --build --no-deps zertiair-apiv2
          echo "End deploying zertiair api v2"