name: Publish zertiair application to pre production stage

on:
  push:
    branches:
      - dev

jobs:
  deploy_backend:
    name: Deploy service
    runs-on: self-hosted
    steps:
      - name: Pulling repo
        run: |
          cd /home/megatro/apps/dockers/dev-zertiair-api/
          echo "Start GIT PULL"
          git restore .
          git pull origin dev
          echo "End GIT PULL"
      - name: Publish backend
        run: |
          cd /home/megatro/apps/dockers
          echo "Start deploying zertiair api v2"
          docker compose up -d --force-recreate --build --no-deps dev-zertiair-api
          echo "End deploying zertiair api v2"